language: node_js
deploy:
  provider: heroku
  api_key:
    secure: Bvw6Esu8sFoG+SrdFxkOUZMSburl60YmqdMkR0MM8lS63Lrlb4fvmtL3LDlSoHVSilwSQ6RI+jywRKDMr3utr6Kn2fWwuIu304ywfN/brlVi/vju4+DQ85enVV+q+Kg8GbJTw+GleI4/H9spzMJqfTLBRwXI0ErupbedyTerCaY=
  app: instacache
  on:
    repo: ARCJ-fc/instacache
    on: master
script: ./run_build.sh